"""add pendientes tables

Revision ID: 8fa4e17944b7
Revises: e64b5d2341a5
Create Date: 2025-12-11 18:35:45.338530

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8fa4e17944b7"
down_revision = "e64b5d2341a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pendientes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.String(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=True),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pendiente_detalles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pendiente_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(), nullable=True),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Float(), nullable=False),
        sa.Column("subtotal", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pendiente_id"],
            ["pendientes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pendiente_detalles")
    op.drop_table("pendientes")
    # ### end Alembic commands ###
